// 表达式：字面量、算术、比较、模板串、三目、逻辑运算的"值是操作数"语义
const a = 7;
const b = 2.5;
console.log(String(a + b));
console.log(String(a - b));
console.log(String(a * b));
console.log(String(a / b));
console.log(String(a % 3));
console.log(String(-a));
console.log(String(1n + 2n));
console.log(String(1n << 62n));
console.log(String(~5n));
console.log(String(0xf0n & 0x3cn));
console.log(String(a < b));
console.log(String(a >= 7));
console.log(String("abc" < "abd"));
console.log(String(a === 7));
console.log(String(a !== 7));
console.log(String(null == undefined));
console.log(String(null === undefined));
console.log(`a=${a} b=${b} sum=${a + b}`);
console.log(String(a > b ? "big" : "small"));
console.log(String(0 || "fallback"));
console.log(String("keep" || "other"));
console.log(String(1 && "second"));
console.log(String(0 && "never"));
console.log(String(null ?? "dflt"));
console.log(String(false ?? "not used"));
console.log(String(!a));
console.log(String(typeof a));
console.log(String(typeof "s"));
console.log(String(typeof 1n));
console.log(String(typeof undefined));
console.log(String(Math.floor(b)));
console.log(String(Math.max(a, 3)));
console.log(String(Math.abs(-b)));
// fround 是为 MIR 的 T_F32 长出来的那个闭合 ABI 口子（ADR-0017 第一刀）：
// 单精度回绕必须真的发生，否则下面三行都会退化成恒等。
console.log(String(Math.fround(0.1 + 0.2)));
console.log(String(Math.fround(1 / 3)));
console.log(String(Math.fround(16777217)));
console.log(String(Math.fround(-0.5)));
console.log(String(Number("42") + 1));
console.log(String(parseInt("ff", 16)));
console.log(String(String(12.5)));
console.log(String((1 / 3).toPrecision(17)));
console.log(String((255).toString(16)));
